### ISSUE TITLE
Consider GitHub Pages instead of Azure Static Web Apps

### ISSUE THREAD

**Issue by atifaziz** [Swimburger/NCrontabTester#2]
Wouldn't GitHub Pages be a simpler deployment of this application instead of Azure Static Web Apps? Both provide hosting of static web resources, but the former seems simpler and more self-contained with regards to the project. Is there any one [Azure Static Web Apps feature](https://docs.microsoft.com/en-us/azure/static-web-apps/overview#key-features) that stands out as necessary for this project?

Of course, this does not have be an “or” decision either.

**Comment by Swimburger** [comment]
I wanted to try Azure Static Web Apps, no other reasons really 😅 

GitHub pages would make sense too.
If it were to be hosted in multiple places, it should contain a canonical-tag to make sure the different hostings aren't hurting each other from a SEO perspective.

**Comment by atifaziz** [comment]
> If it were to be hosted in multiple places, it should contain a canonical-tag to make sure the different hostings aren't hurting each other from a SEO perspective.

Great point!

**Comment by Swimburger** [comment]
After having experimented with GitHub pages and Azure SWA, Azure SWA is a lot more optimized to host static web apps and Blazor WASM in general. I will continue hosting the app using Azure SWA.
